branch-defaults:
  master:
    environment: Group10-Agile-Command-Central-Web-dev
    group_suffix: null
environment-defaults:
  Group10-Agile-Command-Central-Web-dev:
    branch: null
    repository: null
global:
  application_name: Group10-Agile-Command-Central-Web
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
